ALTER TABLE "student_assessments" ADD CONSTRAINT "student_assessments_id_student_id_unique" UNIQUE("id","student_id");--> statement-breakpoint
ALTER TABLE "adjustments" ADD CONSTRAINT "adjustments_assessment_id_student_id_fk" FOREIGN KEY ("assessment_id","student_id") REFERENCES "public"."student_assessments"("id","student_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ledger_entries" ADD CONSTRAINT "ledger_entries_assessment_id_student_id_fk" FOREIGN KEY ("assessment_id","student_id") REFERENCES "public"."student_assessments"("id","student_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_assessment_id_student_id_fk" FOREIGN KEY ("assessment_id","student_id") REFERENCES "public"."student_assessments"("id","student_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notification_deliveries" ADD COLUMN IF NOT EXISTS "claimed_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "notification_deliveries" ADD COLUMN IF NOT EXISTS "lease_expires_at" timestamp with time zone;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "notification_deliveries_status_lease_idx" ON "notification_deliveries" USING btree ("status","lease_expires_at");--> statement-breakpoint
ALTER TABLE "payment_submissions" ADD COLUMN IF NOT EXISTS "legacy_reviewer_unknown" boolean DEFAULT false NOT NULL;--> statement-breakpoint
UPDATE "payment_submissions" SET "legacy_reviewer_unknown" = true WHERE "status" IN ('APPROVED', 'REJECTED') AND "reviewed_by_user_id" IS NULL;--> statement-breakpoint
ALTER TABLE "payment_submissions" DROP CONSTRAINT IF EXISTS "payment_submissions_lifecycle_consistent";--> statement-breakpoint
ALTER TABLE "payment_submissions" ADD CONSTRAINT "payment_submissions_lifecycle_consistent" CHECK (("payment_submissions"."status" = 'PENDING_VERIFICATION' AND "payment_submissions"."reviewed_by_user_id" IS NULL AND "payment_submissions"."reviewed_at" IS NULL AND "payment_submissions"."rejection_reason" IS NULL AND "payment_submissions"."approved_payment_id" IS NULL AND "payment_submissions"."legacy_reviewer_unknown" = false) OR ("payment_submissions"."status" = 'APPROVED' AND "payment_submissions"."approved_payment_id" IS NOT NULL AND "payment_submissions"."rejection_reason" IS NULL AND (("payment_submissions"."legacy_reviewer_unknown" = false AND "payment_submissions"."reviewed_by_user_id" IS NOT NULL AND "payment_submissions"."reviewed_at" IS NOT NULL) OR ("payment_submissions"."legacy_reviewer_unknown" = true AND "payment_submissions"."reviewed_by_user_id" IS NULL AND "payment_submissions"."reviewed_at" IS NULL))) OR ("payment_submissions"."status" = 'REJECTED' AND "payment_submissions"."approved_payment_id" IS NULL AND "payment_submissions"."rejection_reason" IS NOT NULL AND length(trim("payment_submissions"."rejection_reason")) > 0 AND (("payment_submissions"."legacy_reviewer_unknown" = false AND "payment_submissions"."reviewed_by_user_id" IS NOT NULL AND "payment_submissions"."reviewed_at" IS NOT NULL) OR ("payment_submissions"."legacy_reviewer_unknown" = true AND "payment_submissions"."reviewed_by_user_id" IS NULL AND "payment_submissions"."reviewed_at" IS NULL))));
